---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Initialize Nginx
      service:
        name: nginx
        state: started
