#- hosts: all
#  remote_user: ubuntu
#  become: yes
#  roles:
#    - install_nginx
#    - install_docker

- hosts: manager
  remote_user: ubuntu
  become: yes
  roles:
    - docker_swarm_manager

- hosts: worker
  remote_user: ubuntu
  become: yes
  roles:
    - docker_swarm_worker

- hosts: manager
  remote_user: ubuntu
  become: yes
  roles:
    - deploy_stack
