---
- name: Install libs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install Docker Compose dependencies
  apt:
    name:
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: yes

- name: Install Docker Module for Python
  pip:
    name: docker
    state: present

- name: Install jsondiff
  pip:
    name: jsondiff
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

