---
- name: Initialize Docker Swarm
  docker_swarm:
    state: present
  register: init_swarm

- name: Get Docker Swarm join token
  set_fact:
    join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"
